name: Deploy
on:
  push:
    branches: [ main ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Build frontend image
        run: |
          docker build -t medportal-frontend ./frontend
      - name: Build backend image
        run: |
          docker build -t medportal-backend ./backend
      - name: Build single-container image (optional)
        run: |
          docker build -t medportal-all .
  # Optional push to registry (requires secrets)
  docker-push:
    needs: docker-build
    runs-on: ubuntu-latest
    if: ${{ secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push images
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/medportal-frontend:latest
            ${{ secrets.DOCKER_USERNAME }}/medportal-backend:latest